name: "@tabler/icons version check"
on:
  workflow_call:
    inputs:
      currentTablerIconsVersion:
        required: true
        type: string

jobs:
  version-check:
    name: "@tabler/icons new version check"
    runs-on: ubuntu-latest

    outputs:
      update-available: ${{ steps.updateAvailable.isNew }}

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - id: updateAvailable
      run: |
        TABLER_VERSION=$(npm view @tabler/icons version)
        TABLER_VERSION=$(npx semver --range "> ${{ inputs.currentTablerIconsVersion }}" "${{env.TABLER_VERSION}}")
        UPDATE_AVAILABLE=${{ env.TABLER_VERSION != '' }}
        echo "isNew=$UPDATE_AVAILABLE" >> $GITHUB_ENV
      continue-on-error: true
