name: "_template: Build Library"

on:
  workflow_call:

jobs:
  manual:
    name: build library
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm install @tabler/icons@latest
    - run: npm run build-schematics
    - run: npm run link-schematics
    - run: npm run generate-icon-components
    - run: npm run build-high-memory
    - run: npm pack dist/bytelabs/ngx-tabler-icons
    - uses: actions/upload-artifact@v4
      with:
        name: ngx-tabler-icons
        path: bytelabs-ngx-tabler-icons-*.tgz
    - run: |
        AVAILABLE_TABLER_VERSION=$(npm view @tabler/icons version)
        echo "AVAILABLE_TABLER_VERSION=$AVAILABLE_TABLER_VERSION" >> $GITHUB_ENV
    - run: |
        git push --follow-tags origin main
