name: "_template: Build Library"

on:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.VAR_PAT }}      

jobs:
  manual:
    name: build library
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Install latest @tabler/icons
      run: npm install @tabler/icons@latest
    
    - name: Build icon generation schematics 
      run: npm run build-schematics
    
    - name: Link schematics
      run: npm run link-schematics
    
    - name: Generate icon components
      run: npm run generate-icon-components

    - name: Commit and Tag Version
      run: npm run release
    
    - name: Build Angular library
      run: npm run build-high-memory
    
    - name: Pack Angular library
      run: npm pack dist/bytelabs/ngx-tabler-icons
    
    - name: Upload packed library artifact
      uses: actions/upload-artifact@v4
      with:
        name: ngx-tabler-icons
        path: bytelabs-ngx-tabler-icons-*.tgz
    
    - name: Update CURRENT_TABLER_ICONS_VERSION variable
      run: |
        TABLER_VERSION=$(npm view @tabler/icons version)
        gh variable set CURRENT_TABLER_ICONS_VERSION --body "$TABLER_VERSION"        
    
    - name: Push changes and tags to origin
      run: |
        git push --follow-tags origin main
