name: "_template: Tabler Icons Version Check"
on:
  workflow_call:
    inputs:
      currentTablerIconsVersion:
        required: true
        type: string
    outputs:
      update-available:
        description: "New version of @tabler/icons is available"
        value: ${{ jobs.version-check.outputs.update-available}}

jobs:
  version-check:
    name: "@tabler/icons new version check"
    runs-on: ubuntu-latest

    env:
      AVAILABLE_TABLER_VERSION: "0.0.0"

    outputs:
      update-available: ${{ steps.updateAvailable.isNew }}

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: |
        AVAILABLE_TABLER_VERSION=$(npm view @tabler/icons version)
        echo "AVAILABLE_TABLER_VERSION=$AVAILABLE_TABLER_VERSION" >> $GITHUB_ENV
    - id: updateAvailable
      run: |
        AVAILABLE_TABLER_VERSION=$(npx semver --range "> ${{ inputs.currentTablerIconsVersion }}" "${{env.AVAILABLE_TABLER_VERSION}}")
        UPDATE_AVAILABLE=${{ env.AVAILABLE_TABLER_VERSION != '' }}
        echo "isNew=$UPDATE_AVAILABLE" >> $GITHUB_ENV
      continue-on-error: true
