name: "Library: Build and Release if new @tabler/icons exists"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  check-tabler-icons:
    runs-on: 'ubuntu-latest'

    steps:
      - id: version-check
        uses: bytelabs-co/ngx-tabler-icons/.github/workflows/_tabler-icons-version-check.tmpl.yaml@main
        with: 
          currentTablerIconsVersion: ${{ vars.CURRENT_TABLER_ICONS_VERSION }}
      
  build-library:
    needs: check-tabler-icons
    if: ${{ needs.check-tabler-icons.outputs.update-available }}

    runs-on: 'ubuntu-latest'

    steps: 
      - uses: bytelabs-co/ngx-tabler-icons/.github/workflows/_build-library.tmpl.yaml@main


