name: "Library: Build and Release if new @tabler/icons exists"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  check-tabler-icons:
    uses: bytelabs-co/ngx-tabler-icons/.github/workflows/_tabler-icons-version-check.tmpl.yaml@main
    with: 
      currentTablerIconsVersion: ${{ vars.CURRENT_TABLER_ICONS_VERSION }}
      
  build-library:
    runs-on: ubuntu-latest
    needs: check-tabler-icons
    if: ${{ needs.check-tabler-icons.outputs.update-available }}
    steps:
      - uses: bytelabs-co/ngx-tabler-icons/.github/workflows/_build-library.tmpl.yaml@main
      - uses: bytelabs-co/ngx-tabler-icons/.github/workflows/_update-tabler-icons-variable.tmpl.yaml@main

