on:
  workflow_dispatch:

jobs:
  manual:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm install @tabler/icons@latest
    - run: npm run build-schematics
    - run: npm run link-schematics
    - run: npm run generate-icon-components
    - run: npm run build-high-memory
    - run: npm pack dist/bytelabs/ngx-tabler-icons
