name: "Library: Build and Release"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-library:
    uses: bytelabs-co/ngx-tabler-icons/.github/workflows/_build-library.tmpl.yaml@main

