name: "Library: Release to NPM"

on:
  workflow_run:
    workflows: ["Library: Build and Release", "Library: Build and Release new @tabler/icons"]
    types:
      - completed

jobs:
  release-library:
    runs-on: ubuntu-latest

    steps:

      - name: Download library artifact
        uses: actions/download-artifact@v4
        with:
          name: ngx-tabler-icons
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to NPM
        run: npm publish bytelabs-ngx-tabler-icons-*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
