name: "@tabler/icons version check"
on:
  workflow_dispatch:

env:
  TABLER_VERSION: "0.0.0"
  TABLER_VERSION_CHECK: ""
  UPDATE_AVAILABLE: false

jobs:
  manual:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: |
        TABLER_VERSION=$(npm view @tabler/icons verison)
        echo "TABLER_VERSION=$TABLER_VERSION" >> $GITHUB_ENV
    - run: |
        TABLER_VERSION_CHECK = $(npx semver --range "> ${{ vars.LATEST_TABLER_ICONS_VERSION }}" "${{env.TABLER_VERSION}}")
        echo "TABLER_VERSION_CHECK=$TABLER_VERSION_CHECK" >> $GITHUB_ENV
    - run: echo "UPDATE_AVAILABLE = true" >> $GITHUB_ENV
      if:  ${{ env.TABLER_VERSION_CHECK != '' }} 
    - run: echo ${{ env.UPDATE_AVAILABLE }}
