name: "@tabler/icons version check"
on:
  workflow_dispatch:

env:
  TABLER_VERSION: "0.0.0"
  UPDATE_AVAILABLE: false

jobs:
  manual:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: |
        TABLER_VERSION=$(npm view @tabler/icons version)
        echo "TABLER_VERSION=$TABLER_VERSION" >> $GITHUB_ENV
    - run: |
        TABLER_VERSION_CHECK=$(npx semver --range "> ${{ vars.LATEST_TABLER_ICONS_VERSION }}" "${{env.TABLER_VERSION}}")
        UPDATE_AVAILABLE=${{ $TABLER_VERSION_CHECK != '' }}
        echo "UPDATE_AVAILABLE=$UPDATE_AVAILABLE" >> $GITHUB_ENV
    - run: echo ${{ env.UPDATE_AVAILABLE }}
