name: "@tabler/icons version check"
on:
  workflow_dispatch:

env:
  TABLER_VERSION: "0.0.0"

jobs:
  version-check:
    name: "@tabler/icons new version check"
    runs-on: ubuntu-latest

    outputs:
      update-available: ${{ steps.updateAvailable.isNew }}

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: |
        TABLER_VERSION=$(npm view @tabler/icons version)
        echo "TABLER_VERSION=$TABLER_VERSION" >> $GITHUB_ENV
    - id: updateAvailable
      run: |
        TABLER_VERSION=$(npx semver --range "> ${{ vars.CURRENT_TABLER_ICONS_VERSION }}" "${{env.TABLER_VERSION}}")
        UPDATE_AVAILABLE=${{ env.TABLER_VERSION != '' }}
        echo "isNew=$UPDATE_AVAILABLE" >> $GITHUB_ENV
      continue-on-error: true
