on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: |        
        gh variable set --env repository TEST_VAR --body "Set from workflow"
