on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.VAR_PAT }}  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - run: |        
        gh variable set TEST_VAR --body "Set from workflow"
